// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8dzr07N3Qp7MPU1oc12bxODZQ_xpRqI',
    appId: '1:303175382290:web:41378dda28e283ee12afcb',
    messagingSenderId: '303175382290',
    projectId: 'nexora-d05d0',
    authDomain: 'nexora-d05d0.firebaseapp.com',
    storageBucket: 'nexora-d05d0.firebasestorage.app',
    measurementId: 'G-4LL45YLKHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwvsWkij8ggjMPUoj2ePbGoeY0ctkMsw',
    appId: '1:303175382290:android:90657bc10949b1a212afcb',
    messagingSenderId: '303175382290',
    projectId: 'nexora-d05d0',
    storageBucket: 'nexora-d05d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrpr3gdp5_OBsnVGwXhOUWmDjhbjFIYE',
    appId: '1:303175382290:ios:a555e7bb5657e3e712afcb',
    messagingSenderId: '303175382290',
    projectId: 'nexora-d05d0',
    storageBucket: 'nexora-d05d0.firebasestorage.app',
    iosBundleId: 'com.example.nexoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrpr3gdp5_OBsnVGwXhOUWmDjhbjFIYE',
    appId: '1:303175382290:ios:a555e7bb5657e3e712afcb',
    messagingSenderId: '303175382290',
    projectId: 'nexora-d05d0',
    storageBucket: 'nexora-d05d0.firebasestorage.app',
    iosBundleId: 'com.example.nexoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG8dzr07N3Qp7MPU1oc12bxODZQ_xpRqI',
    appId: '1:303175382290:web:45a61e0bb16a96db12afcb',
    messagingSenderId: '303175382290',
    projectId: 'nexora-d05d0',
    authDomain: 'nexora-d05d0.firebaseapp.com',
    storageBucket: 'nexora-d05d0.firebasestorage.app',
    measurementId: 'G-JEZ3TJJ3Z3',
  );
}
